### ISSUE TITLE
gem installation failure with http authentication

### ISSUE THREAD

**Issue by ngram** [ranguba/rroonga#128]
Gem Installation process is failed with http authentication proxy. 

Log is here.
Environment: Windows8.1
Ruby version: ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]

```
C:\Users\ngram>set http_proxy=http://test:testpass@192.168.22.128:8080
C:\Users\ngram>gem install rroonga --verbose
...
Building native extensions.  This could take a while...
C:/bin/Ruby21/bin/ruby.exe extconf.rb
checking for GCC... yes
checking for Win32 OS... yes
downloading http://packages.groonga.org/windows/groonga/groonga-6.0.0-x86.zip...
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/bin/Ruby21/bin/ruby
C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:353:in `open_http': 407 Proxy Authentic
ation Required  (OpenURI::HTTPError)
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:724:in `buffer_open'
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:210:in `block in open_loop
'
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:208:in `catch'
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:208:in `open_loop'
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:149:in `open_uri'
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:704:in `open'
        from C:/bin/Ruby21/lib/ruby/2.1.0/open-uri.rb:34:in `open'
        from extconf.rb:86:in `download'
        from extconf.rb:118:in `extract_groonga_win32_binary'
        from extconf.rb:71:in `block in install_groonga_locally'
        from extconf.rb:69:in `chdir'
        from extconf.rb:69:in `install_groonga_locally'
        from extconf.rb:264:in `install_local_groonga'
        from extconf.rb:274:in `<main>'
ERROR:  Error installing rroonga:
        ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in C:/bin/Ruby21/lib/ruby/gems/2.1.0/gems/rroong
a-6.0.0 for inspection.
Results logged to C:/bin/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0
/rroonga-6.0.0/gem_make.out
```

**Comment by kou** [comment]
Thanks for your report.
The transcript shows another problem.

`gem install rroonga` on Windows should install x86-mingw32 version or x64-mingw32 version listed at https://rubygems.org/gems/rroonga . They include binary. But your transcript shows it will install source only version. It's the another problem.

Ruby 2.2 or 2.3 may solve the another problem.

**Comment by ngram** [comment]
I didn't realize that problem.
If I check or fix it, I let you know the details.

**Comment by kou** [comment]
> If I check or fix it, I let you know the details.

Thanks!
