### ISSUE TITLE
drilldownの計算機能に対応

### ISSUE THREAD

**Issue by kou** [ranguba/rroonga#43]
[Groonga 4.1.1](http://groonga.org/ja/blog/2015/01/29/release.html)でdrilldownに計算機能が追加された。

Rroongaからもこの機能を使えるようにしたい。具体的には次のことができるようになっているとよいはず。

  * `Groonga::Table#drilldown`に`:calc_target => column, :calc_types => [:min, :max, :sum, :average]}`オプションを指定できるようにする。
  * `Groonga::Record`の`#min`, `#max`, `#sum`, `#average` で↑の結果を取得できるようにする。
  * ↑のドキュメントを書く

`Groonga::Table#drilldown`を実装するにあたりGroongaの[lib/proc.c](https://github.com/groonga/groonga/blob/master/lib/proc.c)の`grn_select_drilldowns()`が参考になるはず。

**Comment by myokoym** [comment]
そもそも複数キーに対応していないかもしれません。
以下のスクリプトの複数キーのケースがエラーになってしまいました。

```ruby
require "groonga"
require "fileutils"

def setup_memos
  @tags = Groonga::PatriciaTrie.create(:name => "Tags", :key_type => "ShortText")

  @memos = Groonga::Hash.create(:name => "Memos", :key_type => "ShortText")
  @memos.define_column("tag", "Tags")
  @memos.define_column("priority", "Int64")

  @memo1 = @memos.add("Groonga1",
                      :tag => "Groonga",
                      :priority => 10)
  @memo2 = @memos.add("Groonga2",
                      :tag => "Groonga",
                      :priority => 20)
  @memo3 = @memos.add("Groonga3",
                      :tag => "Groonga",
                      :priority => 40)
  @memo4 = @memos.add("Mroonga1",
                      :tag => "Mroonga",
                      :priority => 50)
  @memo5 = @memos.add("Mroonga2",
                      :tag => "Mroonga",
                      :priority => 25)
  @memo6 = @memos.add("Mroonga3",
                      :tag => "Mroonga",
                      :priority => 10)
  @memo7 = @memos.add("Rroonga1",
                      :tag => "Rroonga",
                      :priority => 25)
  @memo8 = @memos.add("Rroonga2",
                      :tag => "Rroonga",
                      :priority => -25)
  @memo9 = @memos.add("Rroonga3",
                      :tag => "Rroonga",
                      :priority => 0)
end

def group(key_or_keys, options={})
  grouped_memos = @memos.group(key_or_keys, options)
  results = grouped_memos.collect do |group|
    [group._key, group.n_sub_records]
  end
  p [key_or_keys, results]
end

def run
  group("tag")
  group(["tag"])
  group(["priority"])
  group(["tag", "priority"])
end

if $0 == __FILE__
  db_path = "db/test.db"
  if File.exist?(db_path)
    FileUtils.rm_rf(File.dirname(db_path))
  end
  FileUtils.mkdir_p("db")
  database = Groonga::Database.create(:path => db_path)
  setup_memos
  run
end
```

実行結果

```
ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]
drilldown-test.rb:61: warning: assigned but unused variable - database
["tag", [["Groonga", 3], ["Mroonga", 3], ["Rroonga", 3]]]
[["tag"], [["Groonga", 3], ["Mroonga", 3], ["Rroonga", 3]]]
[["priority"], [[10, 2], [20, 1], [40, 1], [50, 1], [25, 2], [-25, 1], [0, 1]]]
drilldown-test.rb:41:in `group': invalid argument: key size unmatch: #<Groonga::Hash id: <257>, name: <Memos>, path: <db/test.db.0000101>, domain: <ShortText>, range: (nil), flags: <>, size: <9>, encoding: <:utf8>, default_tokenizer: (nil), token_filters: [], normalizer: (nil)> (Groonga::InvalidArgument)
hash.c:2128: grn_hash_add()
	from drilldown-test.rb:41:in `group'
	from drilldown-test.rb:52:in `run'
	from drilldown-test.rb:63:in `<main>'

```
