### ISSUE TITLE
Table#selectでRegexp型を受け入れ

### ISSUE THREAD

**Issue by myokoym** [ranguba/rroonga#67]
#62

以下の記法で全文検索できること。

```
selected_items = items.select do |record|
  record.title =~ /Ruby/
end
```

"Ruby"を含むレコード（"A Ruby Library"など）がヒットすること。

**Comment by myokoym** [comment]
このissueでは前方一致検索は実装せず、Regexp型を受け入れることだけを目的にする。
Regexp型での前方一致検索は #70 で実施する。

**Comment by myokoym** [comment]
#65 が終わったので、こちらに着手します。

まずはテストを書いて失敗させます。
次に、 https://github.com/ranguba/rroonga/issues/64#issuecomment-89239373 の部分を実装します。

**Comment by kou** [comment]
先に方針をメモしておくのはよい進め方ですね！

**Comment by myokoym** [comment]
テストを書いて失敗することを確認しました。

テストコード:

```ruby
class ExpressionBuilderTest < Test::Unit::TestCase
  ...
  class RegexpSearchTest < self
    def setup_tables
      Groonga::Schema.define do |schema|
        schema.create_table("Users",
                            :type => :hash,
                            :key_type => "ShortText") do |table|
          table.short_text("name")
        end

        schema.create_table("Terms",
                            :type => :patricia_trie,
                            :key_type => "ShortText",
                            :default_tokenizer => "TokenRegexp",
                            :normalizer => "NormalizerAuto") do |table|
          table.index("Users.name")
        end
      end

      @users = Groonga["Users"]
    end

    def setup_data
      @users.add("sato",   :name => "taro sato")
      @users.add("suzuki", :name => "Shiro SUZUKI")
      @users.add("ito",    :name => "Takashi Ito")
    end

    class BlockTest < self
      def test_match
        result = @users.select do |record|
          record["name"] =~ /sh/
        end
        assert_equal(["suzuki", "ito"],
                     result.collect {|record| record.key.key})
      end

      def test_not_match
        result = @users.select do |record|
          record["name"] =~ /abcabcabc/
        end
        assert_equal([],
                     result.collect {|record| record.key.key})
      end
    end

    class QueryStringTest < self
      def test_match
        result = @users.select("name:~t")
        assert_equal(["sato", "ito"],
                     result.collect {|record| record.key.key})
      end

      def test_not_match
        result = @users.select("name:~x")
        assert_equal([],
                     result.collect {|record| record.key.key})
      end
    end
  end
```

実行結果:

```
Loaded suite test/run-test
Started
ExpressionBuilderTest: 
  RegexpSearchTest: 
    BlockTest: 
      test_match:					E
===============================================================================
Error: test_match(ExpressionBuilderTest::RegexpSearchTest::BlockTest)
: TypeError: bulked object should be one of [nil, true, false, String, Symbol, Integer, Float, Time, Groonga::Object, Groonga::Record]: /sh/
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:317:in `append_constant'
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:317:in `build'
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:92:in `build_expression'
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:47:in `build'
/home/myokoym/work/groonga/rroonga/test/test-expression-builder.rb:280:in `select'
/home/myokoym/work/groonga/rroonga/test/test-expression-builder.rb:280:in `test_match'
     277: 
     278:     class BlockTest < self
     279:       def test_match
  => 280:         result = @users.select do |record|
     281:           record["name"] =~ /sh/
     282:         end
     283:         assert_equal(["suzuki", "ito"],
===============================================================================
: (0.031947)
      test_not_match:					E
===============================================================================
Error: test_not_match(ExpressionBuilderTest::RegexpSearchTest::BlockTest)
: TypeError: bulked object should be one of [nil, true, false, String, Symbol, Integer, Float, Time, Groonga::Object, Groonga::Record]: /abcabcabc/
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:317:in `append_constant'
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:317:in `build'
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:92:in `build_expression'
/home/myokoym/work/groonga/rroonga/lib/groonga/expression-builder.rb:47:in `build'
/home/myokoym/work/groonga/rroonga/test/test-expression-builder.rb:288:in `select'
/home/myokoym/work/groonga/rroonga/test/test-expression-builder.rb:288:in `test_not_match'
     285:       end
     286: 
     287:       def test_not_match
  => 288:         result = @users.select do |record|
     289:           record["name"] =~ /abcabcabc/
     290:         end
     291:         assert_equal([],
===============================================================================
: (0.030534)
    QueryStringTest: 
      test_match:					.: (0.030459)
      test_not_match:					.: (0.029984)

Finished in 0.123403185 seconds.
------
4 tests, 2 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
------
32.41 tests/s, 16.21 assertions/s
```

次は実装に入ります。

**Comment by kou** [comment]
結果も載せてあっていいですね！

`QueryStringTest`はこれとは関係ないのでこれは別のpull requestにわけて先にください。

あと、検索結果の順序は不定なので、

```ruby
result.collect {|record| record.key.key}.sort
```

というようにソートしてから比較するようにしてください。

**Comment by myokoym** [comment]
わかりました。
pushしてしまったのでコミットメールが流れてしまいましたが、
手元で修正して`push -f`してからpull requestします。

**Comment by myokoym** [comment]
#89 で対応したのでcloseします。次は #70 に進みます。
